networks:
  default:
    name: my_custom_network
    external: false

services:
  # Core service
  mysql-core:
    image: mysql:8.0
    container_name: mysql-core
    environment:
      MYSQL_ROOT_PASSWORD: Cjql195jsov
      MYSQL_DATABASE: chain_optimizer_schema
    ports:
      - "3306:3306"
    volumes:
      - ./core/mysql:/var/lib/mysql
      - ./core/database/schema:/docker-entrypoint-initdb.d
    networks:
      - default

  chainoptim-core:
    image: tudoraorban/chainoptim-core:latest
    container_name: chainoptim-core
    depends_on:
      - mysql-core
      - redis
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker-dev
      AWS_REGION: eu-central-1
    volumes:
      - C:/Users/tudor/.aws:/root/.aws
    networks:
      - default

  # Notifications service
  mysql-notifications:
    image: mysql:8.0
    container_name: mysql-notifications
    environment:
      MYSQL_ROOT_PASSWORD: Cjql195jsov
      MYSQL_DATABASE: chainoptim-notifications-db
    ports:
      - "3307:3307"
    volumes:
      - ./notifications/mysql:/var/lib/mysql
      - ./notifications/database/schema:/docker-entrypoint-initdb.d
    networks:
      - default

  chainoptim-notifications:
    image: tudoraorban/chainoptim-notifications:latest
    container_name: chainoptim-notifications
    depends_on:
      - mysql-notifications
      - redis
      - kafka
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker-dev
    networks:
      - default

  # Distributed services
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - default

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092, OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092, OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - default


volumes:
  mysql-data:
  mysql-notifications-data: