apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainoptim-vault
spec:
  replicas: 0
  selector:
    matchLabels:
      app: chainoptim-vault
  template:
    metadata:
      labels:
        app: chainoptim-vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          ports:
            - containerPort: 8200
          args:
          - "server"
          - "-dev"
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root"
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: "0.0.0.0:8200"
            - name: VAULT_ADDR
              value: "http://0.0.0.0:8200"
---
apiVersion: v1
kind: Service
metadata:
  name: chainoptim-vault
spec:
  ports:
    - port: 8200
      targetPort: 8200
  selector:
      app: chainoptim-vault