apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainoptim-config-server
  labels:
    app: chainoptim-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chainoptim-config-server
  template:
    metadata:
      labels:
        app: chainoptim-config-server
    spec:
      initContainers:
      - name: setup
        image: alpine:latest
        command:
          - /bin/sh
          - -c
          - |
            apk add --no-cache curl && \
            TOKEN=$(curl -s http://chainoptim-vault:8200/v1/secret/data/config-server | jq -r '.data.data.token') && \
            echo "spring.cloud.vault.token=$TOKEN" > /etc/config/bootstrap.properties
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      containers:
      - name: chainoptim-config-server
        image: chainoptim-config-server:latest
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        env:
        - name: SPRING_CONFIG_ADDITIONAL_LOCATION
          value: file://config/bootstrap.properties
      volumes:
      - name: config-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: chainoptim-config-server
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: chainoptim-config-server