apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainoptim-config-server
  labels:
    app: chainoptim-config-server
spec:
  replicas: 0
  selector:
    matchLabels:
      app: chainoptim-config-server
  template:
    metadata:
      labels:
        app: chainoptim-config-server
    spec:
      containers:
        - name: chainoptim-config-server
          image: tudoraorban/chainoptim-config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_APPLICATION_NAME
              value: "chainoptim-config-server"
            - name: SERVER_PORT
              value: "8888"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: "https://github.com/TudorOrban/ChainOptim-config"
            - name: SPRING_CLOUD_VAULT_HOST
              value: "chainoptim-vault"
            - name: SPRING_CLOUD_VAULT_PORT
              value: "8200"
            - name: SPRING_CLOUD_VAULT_SCHEME
              value: "http"
            - name: SPRING_CLOUD_VAULT_TOKEN
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: chainoptim-config-server
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: chainoptim-config-server
