apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainoptim-storage
  labels:
    app: chainoptim-storage

spec:
  replicas: 0
  selector:
    matchLabels:
      app: chainoptim-storage
  template:
    metadata:
      labels:
        app: chainoptim-storage
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '8083'
    spec:
      containers:
      - name: chainoptim-storage
        image: tudoraorban/chainoptim-storage:latest
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker-dev
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: chainoptim-storage
  labels:
    app: chainoptim-storage
spec:
  type: NodePort
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
    nodePort: 31280
  selector:
    app: chainoptim-storage